spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
  jpa:
    hibernate:
     ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

msg: I am test-refresh Env
